### PR TITLE
Fixed syntax error in pages/content-ui/package.json

### PR DESCRIPTION
**Pull request by codergigachad**
> `*` Please fill in the required items.

## Priority*

- [x] High: This PR needs to be merged first for other tasks.
- [ ] Middle: This PR should be merged quickly to prevent conflicts due to common changes. (default)
- [ ] Low: This PR does not affect other tasks, so it can be merged later.

## Purpose of the PR*
Tailwind build was not working in content-ui during hmr due to syntax error.

## Changes*
Changed the package.json file of pages/content-ui

### CODE REVIEW

**Review by Jonghakseo — COMMENTED** [review]
@codergigachad 

Can you explain exactly what problem you're trying to solve? I'm wondering what the `syntax error` is referring to, and what the issue is. 

Is it an issue with Windows?

**Comment by PatrykKuniczak** [comment]
@Jonghakseo It works perfect for Win also.
IDN what's the reason of this PR

**Comment by codergigachad** [comment]
During hot module reload the changed tailwind classes inside content scripts doesn't build in the css file because of wrong build command in package.json. It doesn't work for me in windows but after I change it to these commands with `pnpm dlx` it starts to work.

**Comment by PatrykKuniczak** [comment]
@codergigachad I see the issue right now, but it's not that easy to fix it, as you done.

You put --watch into ```build:tailwindcss``` what's cause never ending build.

I fixed it in #654.

I need to close it, because it's fork, i wanted to open PR, to this but it isn't possible, and i don't want to push my commits here 😄 

I hope, you won't feel gutted, and want to contribute more 😸

**Comment by codergigachad** [comment]
No problem, I like this repo and I would like to contribute in the future as well.

**Pull request closed without merging**
