### PR TITLE
Improve Content-UI Injection with Enhanced Package

### PR DESCRIPTION
**Pull request by Leizhenpeng**

### CODE REVIEW

**Comment by PatrykKuniczak** [comment]
@Leizhenpeng Are you eager to move forward?

**Comment by Leizhenpeng** [comment]
I will move. I am a little busy at work now. I will try to do it this weekend.！

**Comment by PatrykKuniczak** [comment]
@Leizhenpeng Don't worry, take your time.

I'm question only for know you're still eager to contribute 😄

**Comment by PatrykKuniczak** [comment]
@Leizhenpeng Keep pushing mate, I keep my fingers crossed 😆

**Comment by PatrykKuniczak** [comment]
I'm closing it because of inactivity, if you want to work on that, feel free to reopen.

**Pull request closed without merging**
