### PR TITLE
[Enhance] modify to detect and reload manifest changes

### PR DESCRIPTION
**Pull request by Jonghakseo**
Fixed https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/261

- Modify the manifest.ts file with the js extension
- The make-manifest plugin watches the manifest file and rebuilds it
- Disable emptyOutDir option only in dev

### CODE REVIEW

**Comment by Jonghakseo** [comment]
https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/53500778/e09a9047-2ece-42e7-96f3-247165ce7251

**Comment by PatrykKuniczak** [comment]
@Jonghakseo 
image

This occur after i start 'npm run dev'

I'd tried to remove node_modules and dist and reinstall, but still occur

**Comment by Jonghakseo** [comment]
> This occur after i start 'npm run dev'
> 
> I'd tried to remove node_modules and dist and reinstall, but still occur

Ow... Probably needs additional processing on Windows. :(

I'll check it now

**Comment by Jonghakseo** [comment]
This error seems to be very common on Windows, and I've found a few things that seem to work.

- https://github.com/dargmuesli/nuxt-cookie-control/issues/14#issuecomment-1446306360

**Pull request merged**
