### PR TITLE
feat(blog): rollup packaging speed optimization

### PR DESCRIPTION
**Pull request by webLiang**
Comparison   6.5s     →    0.3s 
image

image

Official reminder：
image

### CODE REVIEW

**Comment by tngflx** [comment]
@webLiang hey man can send me the web link of the docs (the image u posted). This is so interesting.

**Comment by webLiang** [comment]
> @webLiang hey man can send me the web link of the docs (the image u posted). This is so interesting.嘿，伙计，可以向我发送文档的网络链接（您发布的图像）。这太有趣了。

Code warehouse：
https://github.com/webLiang/chrome-extension-boilerplate-react-vite/tree/mxl

**Comment by Jonghakseo** [comment]
Wow... I'll check tomorrow!

**Review by Jonghakseo — APPROVED** [review]
LGTM...! It's awesome!

**Comment by Jonghakseo** [comment]
@all-contributors please add @webLiang for code

**Pull request merged**
