### PR TITLE
style: add a link on the logo to redirect to the GitHub homepage

### PR DESCRIPTION
**Pull request by RSS1102**
> `*` Please fill in the required items.

## Priority*

- [ ] High: This PR needs to be merged first for other tasks.
- [ ] Middle: This PR should be merged quickly to prevent conflicts due to common changes. (default)
- [x] Low: This PR does not affect other tasks, so it can be merged later.

## Purpose of the PR*

I just think we should add a quick link to the homepage, which can quickly locate the repo homepage

## Changes*

Add a redirect link to the GitHub homepage for each app logo.

## How to check the feature

Click on each app logo, open a new tab in the browser, and point to the GitHub homepage.

## Reference

none

---
Do I need to add a test for correct link redirection?

### CODE REVIEW

**Comment by PatrykKuniczak** [comment]
It's nice, but there's some changes, no `no changes` :)

**Review by PatrykKuniczak — APPROVED** [review]
LGTM

But update description, it's crucial to describe what was affected, it can help us or anybody which will open this PR in the future ;)

**Comment by RSS1102** [comment]
> LGTM
> 
> But update description, it's crucial to describe what was affected, it can help us or anybody which will open this PR in the future 😄

sorry ,It was my mistake,I have updated the instructions.

**Comment by PatrykKuniczak** [comment]
> > LGTM
> > But update description, it's crucial to describe what was affected, it can help us or anybody which will open this PR in the future 😄
> 
> sorry ,It was my mistake,I have updated the instructions.

No problem, thanks for your contribution

**Review by Jonghakseo — APPROVED** [review]
LGTM

**Pull request merged**
