### PR TITLE
feat/use ts for tw and postcss configs

### PR DESCRIPTION
**Pull request by PatrykKuniczak**
> `*` Please fill in the required items.

## Priority*

- [ ] High: This PR needs to be merged first for other tasks.
- [ ] Middle: This PR should be merged quickly to prevent conflicts due to common changes. (default)
- [x] Low: This PR does not affect other tasks, so it can be merged later.

## Purpose of the PR*
solved #527

I have done it because i want to be 'One Step Closer' (How knoows :))
To have full support to .ts

## Changes*
I have changes .js to .ts and done neccessary changes to fit ts

## How to check the feature
Edit some tw classes :)

### CODE REVIEW

**Comment by Jonghakseo** [comment]
I face this error

`[Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /chrome-extension-boilerplate-react-vite/pages/popup): [SyntaxError] Unexpected token 'export'`

스크린샷 2024-08-28 오후 5 29 03

**Comment by PatrykKuniczak** [comment]
> I face this error
> 
> `[Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /chrome-extension-boilerplate-react-vite/pages/popup): [SyntaxError] Unexpected token 'export'`
> 
> 스크린샷 2024-08-28 오후 5 29 03
> 

Maybe that's issue with "module" in package.json, because i've rememberd it happened in one issue certainly on mac, but not on Win, i will take a look after work

**Comment by PatrykKuniczak** [comment]
@Jonghakseo this will be fixed by #683 merge it and rebase here, and try on your machine :)

**Review by Jonghakseo — APPROVED** [review]
LGTM

**Pull request merged**
