### PR TITLE
separate eslint and prettier package

### PR DESCRIPTION
**Pull request by wonkyDD**
close https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/515

# eslint package

* Set .eslintignore to ignorePatterns in base.js of the eslint package

* Move all eslint-related packages from the root package.json to the eslint package

* Added the following sections to the package.json of each package

```package.json
{
  "devDependencies": {
    "@chrome-extension-boilerplate/eslint-config": "workspace:*",
    "eslint": "8.57.0"
  },
  "eslintConfig": {
    "root": true,
    "extends": [
      "@chrome-extension-boilerplate/eslint-config/base"
    ]
  },
}
```

# prettier package

* Added the following sections to the package.json of each package

```package.json
{
  "devDependencies": {
    "@chrome-extension-boilerplate/prettier-config": "workspace:*",
  },
  "prettier": "@chrome-extension-boilerplate/prettier-config"
}
```

# Other details

* Applied the above changes to the package.json of the tailwind-config package and added a tsconfig file

* Added exclude to the base file of the existing tsconfig package

* The following warning keeps occurring due to version issues when linting (this is not limited to this PR)

```
WARNING: You are currently running a version of TypeScript
which is not officially supported by @typescript-eslint/typescript-estree
SUPPORTED TYPESCRIPT VERSIONS: >=4.3.5 <5.4.0
```

### CODE REVIEW

**Comment by Jonghakseo** [comment]
I faced `Cannot find moudle` error in my Webstorm. :(

```
Error: Failed to load plugin 'react' declared in 'package.json » @chrome-extension-boilerplate/eslint-config/base': Cannot find module 'eslint-plugin-react'
```

**Comment by PatrykKuniczak** [comment]
@wonkyDD Any moves forward?

**Comment by wonkyDD** [comment]
@Jonghakseo  @PatrykKuniczak
I apologize for the delayed update.
I have some scheduled commitments for a while, so it will be difficult to focus on this.

**Comment by Jonghakseo** [comment]
> I apologize for the delayed update.
> I have some scheduled commitments for a while, so it will be difficult to focus on this.

@wonkyDD 

No need to apologize! Thank you for always being so kind to this project. Your contributions are very helpful to me and other developers :)

**Comment by PatrykKuniczak** [comment]
> @Jonghakseo @PatrykKuniczak I apologize for the delayed update. I have some scheduled commitments for a while, so it will be difficult to focus on this.

I also has a lot to do IRL and now i'm more free to do sth, i totally understand you :)

**Comment by Jonghakseo** [comment]
To keep ESlint behavior inside the IDE in Webstorm, I ended up having to install eslint config and plugin inside each package (page). While this worked fine via the CLI, I ran into issues with IDE support, which resulted in a drop in DX. 🫠

**Comment by PatrykKuniczak** [comment]
@Jonghakseo You suggesting to don't separate these packages?

**Comment by Jonghakseo** [comment]
> @Jonghakseo You suggesting to don't separate these packages?

IMHO.... Yep... 
At least, users who use a WebStorm are uncomfortable with this separation.

**Comment by PatrykKuniczak** [comment]
@Jonghakseo I using webstorm :)
On that condition i think, we can close this thread

**Pull request closed without merging**
