### PR TITLE
[Enhance] Modify to let the plugin do the build completion detection not file system.

### PR DESCRIPTION
**Pull request by Jonghakseo**
Fixed https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/184

### CODE REVIEW

**Review by PatrykKuniczak — CHANGES_REQUESTED** [review]
Works better, but after rebuild is done, the plugin don't be displaying properly.

THIS HAPPENED ONLY WHEN I'M ADD CODE

Looks like this:
image

I must reopen it manually and then it works, error from #184 don't ocurr, but it's the same case, i must click outside and after that, open again manually and then i can see my changes.

PS: I see also error like this on reload:

THIS HAPPENED ONLY WHEN I'M DELETE CODE

image
image

The entire script is stoped on that error.

Intresting thing is, when i have this small window, from first screen, the code reload is working well, i can remove or add a hundreds line of code, and nothing break, cause plugin don't need to be reloaded, cause it's break already.

If i refresh it manually/reopen, it break again following cases from above

**Comment by PatrykKuniczak** [comment]
@Jonghakseo And the question, we need to create this warn
image

IMO it's a little annoying, if i see i had an error, but in real i don't have, it's only information, clearing it don't work, cause after clean, we use it again, and after each socket disconnect this warn goes into this console.

**Comment by Jonghakseo** [comment]
> IMO it's a little annoying, if i see i had an error, but in real i don't have, it's only information, clearing it don't work, cause after clean, we use it again, and after each socket disconnect this warn goes into this console.

@PatrykKuniczak 
Good. I fixed it to output a log instead of a warning and try to reconnect every 1 second.

**Comment by Jonghakseo** [comment]
> Works better, but after rebuild is done, the plugin don't be displaying properly.
> 
> THIS HAPPENED ONLY WHEN I'M ADD CODE
> ....

In my case, the problem was intermittently clearing files while waiting for a build of an existing file. I've modified the options, can you give it another try?

**Review by PatrykKuniczak — APPROVED** [review]
Works perfect <3

**Pull request merged**
